### ISSUE TITLE
Renamed from Flash?

### ISSUE THREAD

**Issue by winkler1** [vesparny/morpheus#2]
Hi,
 I run React.rocks, this looked interesting. Good name. I see the link to https://alessandro.arnodo.net/introducing-morpheus/ from the README is 404 and this looks very new, so please close this issue when you're ready for it to be featured :)
Thanks,
Jeff

**Comment by vesparny** [comment]
Hi Jeff,
I still have some stuff to fix, then I'll try to do the first official release, and an help to spread the word would be awesome.

Thanks

**Comment by vesparny** [comment]
Done, the into post is now live at https://alessandro.arnodo.net/2015/01/07/introducing-morpheus/
