### ISSUE TITLE
logo design

### ISSUE THREAD

**Issue by vesparny** [vesparny/morpheus#3]

**Comment by willyg302** [comment]
If it's named after Morpheus of _The Matrix_ fame as I'm assuming, I think the logo could incorporate either the [glasses shape](http://ak1.ostkcdn.com/images/products/3/L945557.jpg) or [two hands](http://www.memedonkey.com/pictures/thumbs/39/thumb-morpheus-pill-meme-of-offering-the-39121.jpg). Either way, there's symmetry which falls directly in line with the isomorphic aspect of the project (one hand is server and one hand is client, etc.). For example, I envisioned the word "MORPHEUS" stretching between the hands, with the M in red and the S in blue.

Great work on the project so far!

**Comment by willyg302** [comment]
Quick mockup to illustrate:

![morpheus-screen](https://cloud.githubusercontent.com/assets/2390474/5793884/1f3095dc-9efa-11e4-8b66-556c8256028a.png)

**Comment by vesparny** [comment]
@willyg302 Thanks for your proposal.
Actually the **Morpheus** name comes from the word isoMORPHic.
I was wondering about creating a logo with only Image, with the text Morpheus just next to it.

Something like this https://ghost.org/about/logos/.
If you have any idea, it would be really appreciated.
I'm not a designer, and I didn't even think about a proper color scheme.

**Comment by tlkh** [comment]
Morpheus somehow seems orange in my mind. A stylised M feels suitable for this. There can be a "long" logo consisting of a stylised M and orpheus and a "short" logo which is just the M.
However, I like @willyg302 's idea of the glasses!

**Comment by vesparny** [comment]
@tlkh yes I like the idea, and I like orange too :)
I'm waiting for some guy into design, because I'm a noob in that field.

**Comment by tsanyqudsi** [comment]
maybe a five dot will do. 

In mathematics, an isomorphism (from the Greek: ἴσος isos "equal", and μορφή morphe "shape") is a homomorphism (or more generally a morphism) that admits an inverse.[note 1] Two mathematical objects are isomorphic if an isomorphism exists between them.

**Comment by tsanyqudsi** [comment]
http://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&ved=0CAQQjBw&url=http%3A%2F%2Fwww.clker.com%2Fcliparts%2F2%2F0%2Fb%2F1%2F11971482861718966437molumen_domino_set_5.svg.med.png&ei=PVHBVPeGKM_g8AXe5oDoCA&bvm=bv.83829542,d.dGc&psig=AFQjCNHIODlgY4p9hh5rVVHsNvufH4sfmA&ust=1422041774362161

**Comment by willyg302** [comment]
Ah I see now!

@tsanyqudsi 's idea is more in line with the Ghost example:

![morpheus-logo](https://cloud.githubusercontent.com/assets/2390474/5868005/7be83cec-a258-11e4-98d1-c781073a4857.png)

I also like the idea of a stylized M, but you have to be careful to strike a balance between getting an idea across (what the M is supposed to look like) and keeping it readable enough so it doesn't just look like "orpheus". Couldn't think of anything right off the bat

**Comment by vesparny** [comment]
@willyg302 Don't you think the logo with five bullets it's a bit empty? Probably with a darker background would be better?

**Comment by tsanyqudsi** [comment]
I'm still at office. Will give u the logo later.

Sent From Sony Z1 Compact

**Comment by eldh** [comment]
Had an idea, so I made a quick sketch. (morpheus glasses, two equal but mirrored shapes…)
![image](https://cloud.githubusercontent.com/assets/612703/5896614/c2897b38-a538-11e4-94c7-af54eec0a1d2.png)

**Comment by vesparny** [comment]
@eldh really like the concept. Mirrored shape, it also recalls the isomorphic concept in someway.

**Comment by eldh** [comment]
@vesparny Yep, that was the thought. :) I'll explore it a bit further after work.

**Comment by vesparny** [comment]
Nice

On January 26, 2015 11:22:00 AM GMT+01:00, Andreas Eldh notifications@github.com wrote:

> @vesparny Yep, that was the thought. :) I'll explore it a bit further
> after work.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vesparny/morpheus/issues/3#issuecomment-71439909

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by eldh** [comment]
Think it works ok. 
![screen shot 2015-01-26 at 20 57 29](https://cloud.githubusercontent.com/assets/612703/5907283/0445fd8e-a59e-11e4-8f19-706b87473e6d.png)

**Comment by tsanyqudsi** [comment]
actually the @eldh version is nicer.

**Comment by vesparny** [comment]
@eldh nice!
Do you think you can think about colors? and on how to have a squared logo?

We need to defined and choose a color scheme for the project.

I really love your idea.

just 2 consideration from a profane:
- maybe the shadow in the bottom of glasses could be darker?
- isn't it better if the glasses were dark? (black?) on a clear background?

**Comment by eldh** [comment]
Gave it another iteration with your suggestions. Worked out well I think. Dark on light makes way more sense (and looks less like eggs). Not sure about colors but tried a teal/orange combo.

As for square logo I'm not sure what you want it for. Icons and such? Just go with the glasses on a colored base I'd say in that case.

:)

![morpheus 2](https://cloud.githubusercontent.com/assets/612703/5927677/95db7306-a674-11e4-9ef6-348b48c399b7.png)
![morpheus 2 1](https://cloud.githubusercontent.com/assets/612703/5927675/95ad17d6-a674-11e4-9a48-a3f674f1a00f.png)
![morpheus 2 3](https://cloud.githubusercontent.com/assets/612703/5927739/0c099df0-a675-11e4-8f0d-4f523ab79b2e.png)

**Comment by vesparny** [comment]
@eldh sorry for the late answer,

I really like what you have done, thanks.

The teal/orange combo sounds great to my eyes.

Don't you think the square logo is a bit empty with only glasses inside?
It might be weird if you imagine it as a favicon or something small.

If you could mix some orange in the squared logo I think we are good :)

I don't know if I'm taking the right example, but for the Ghost project, you can download pngs with logo on dark and white background, and also vectorial svg and psd files.
Do you think this is doable for us?
https://ghost.org/about/logos/

**Comment by vesparny** [comment]
moreover we need to identify:
- color scheme ( providing hexadecimal codes for orange and green)
- font used for the sign "Morpheus" ( may we find some OS font?)

**Comment by eldh** [comment]
Sure! I'll work some more on the squared logo and I'll try to make sure it looks nice in favicon size. 

I could do a PR to somewhere (?) with the logos in svg and png format along with perhaps a scss file with variables for colors and fonts? No psd:s though, since I made this in Sketch. :)

These examples use Avenir Next Condensed, but Ubuntu Condensed is very similar and available as a free web font from Google Fonts, so we could easily swap to that.

**Comment by vesparny** [comment]
Nice !!

What about making a PR creating a **branding** folder in the root of the project?

I'm wondering about creating an orgs account for the project, as soon as I'll ready we can also end up creating a dedicated project for that.

Can't wait to integrate the new graphics and colours in the default theme ;)

**Comment by eldh** [comment]
Sounds good! 

I'll get to work on it tonight or tomorrow, I think.

**Comment by eldh** [comment]
I hit a bit of a wall trying to make it work well in a square and on dark background. So, back to the drawing board... And I came up with something else that I think works quite well. Same shapes, but now used as red and blue pills. Still captures the isomorphism and a (not so subtle) reference to The Matrix. What to you think? 
![morpheus 2 3 1 1](https://cloud.githubusercontent.com/assets/612703/5991722/a3021acc-aa01-11e4-9d81-fc386530bfc8.png)
![morpheus 2 3 1](https://cloud.githubusercontent.com/assets/612703/5991719/a2fad1a4-aa01-11e4-92c3-690bac28bfc6.png)
![morpheus 2 3](https://cloud.githubusercontent.com/assets/612703/5991720/a2fca9d4-aa01-11e4-879e-15db126d63e9.png)

Also made some buttons and text real quick to get some sense of how the color scheme works 'in action'. 
![morpheus 2 4](https://cloud.githubusercontent.com/assets/612703/5991721/a2fdc4b8-aa01-11e4-8bc6-dc19aab50a87.png)

Fonts used are Ubuntu Condensed for the logo, Source Sans Pro and Source Serif Pro in the UI exploration.

**Comment by vesparny** [comment]
This is awesome.
I really like colors, fonts and shapes.

Moreover you have created a good balance between shapes and background space.

What about having the 2 pills exactly at the same high level, rather than having the blue one just above the other?
![drawing](https://cloud.githubusercontent.com/assets/82070/5992950/6dfdb528-aa3f-11e4-93b7-fecb52d248c8.png)

Not sure my sketch makes sense, probably having the pills on different levels is better.
Btw what you did is stunning, I think we are close to have a visual identity for this project.

Thanks for you effort @eldh

**Comment by vesparny** [comment]
No no, your solution is way better, definitely!
You can forget my previous comment.

**Comment by eldh** [comment]
:+1: Glad you like it! I'll get to work on that PR.

**Comment by vesparny** [comment]
thanks to @eldh for the great work, I'll adapt to the new graphic ASAP

**Comment by soundyogi** [comment]
@eldh this is really nice! fits on so many levels

**Comment by sergeylukin** [comment]
@eldh last revision set of your logo looks awesome! Three cheers for checking color scheme "in action".
It was so interesting to follow the way you people went through here in this thread to get to the final version. Very impressive to see how Github platform is useful in so many ways.
